### ISSUE TITLE
500 if Authorization header not supplied

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#30] opened 2020-04-15 20:14 UTC
This (with the token filled in) returns a big JSON response:
```
curl 'https://search-api.dev.hubmapconsortium.org/search' --compressed \
  -H 'Content-Type: application/json;charset=utf-8' \
  -H 'Authorization: Bearer AgBad0p6BDe8MbX.......MKK7UkDzE8bIq24K' \
  --data '{}'
```

Without the `Authorization` header:
```
$ curl 'https://search-api.dev.hubmapconsortium.org/search' --compressed \
>   -H 'Content-Type: application/json;charset=utf-8' \
>   --data '{}'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

- Any time you return 500, I think it's a problem?
- More generally, I think the idea is that unlogged-in users should still see at least a minimal set of records?

**Comment by yuanzhou** [comment] 2020-04-16 14:02
The `Authorization` header is optional. You can still get back elasticsearch results without providing a token. But those are the results marked as "Open" to the public. The 500 error might be caused by something else. I'll look into that.

**Comment by yuanzhou** [comment] 2020-04-30 14:43
Addressed in this new deployment.

**Closed by yuanzhou** 2020-04-30 14:43 UTC
Labels: bug
